[SENSORS] sensors.shooteru: Add missing headers
Fixes build failures:
device/htc/shooteru/libsensors/LightSensor.cpp:25:31: fatal error: linux/lightsensor.h: No such file or directory
device/htc/shooteru/libsensors/ProximitySensor.cpp:25:34: fatal error: linux/capella_cm3602.h: No such file or directory
device/htc/shooteru/libsensors/AkmSensor.cpp:25:27: fatal error: linux/akm8975.h: No such file or directory

Change-Id: I649b868720378d24bed52caa033bd01e75c66f26